name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add or update the remote
          git remote set-url space https://Usaxena27:${HF_TOKEN}@huggingface.co/spaces/Usaxena27/Search_Engine_LLM 2>/dev/null || \
          git remote add space https://Usaxena27:${HF_TOKEN}@huggingface.co/spaces/Usaxena27/Search_Engine_LLM
          
          # Push main branch to Hugging Face Space
          git push --force space main
